Use oslo_log instead of python logging
Pypowervm exceptions are being translated with oslo_i18n and in
some cases these exceptions are being logged.  The python logging
module doesn't properly handle Message objects that get produced
by oslo_i18n.  The result is an exception like:

UnicodeError: Message objects do not support str() because they
may contain non-ascii characters. Please use unicode() or
translate() instead.
Logged from file job.py, line 134

Change-Id: I12476537d66c7da12b64b1adfd7f2ec0332e35d5