Taskflow 1.31.0 causes circular dependency that fails tox
tox will fail when installing taskflow 1.31.0. Enforce our requirements
to taskflow 1.30.0 or earlier.

Example error:
12:56:13 Failed to import test module: pypowervm.tests.tasks.test_hdisk
12:56:13 Traceback (most recent call last):
12:56:13   File "/tmp/jenkins/workspace/pypowervm/.tox/py34/lib/python
3.4/site-packages/unittest2/loader.py", line 456, in _find_test_path
12:56:13     module = self._get_module_from_name(name)
12:56:13   File "/tmp/jenkins/workspace/pypowervm/.tox/py34/lib/python
3.4/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
12:56:13     __import__(name)
12:56:13   File "/tmp/jenkins/workspace/pypowervm/pypowervm/tests/tasks
/test_hdisk.py", line 21, in <module>
12:56:13     from pypowervm.tasks import hdisk
12:56:13   File "/tmp/jenkins/workspace/pypowervm/pypowervm/tasks/hdis
k.py", line 28, in <module>
12:56:13     import pypowervm.tasks.storage as tsk_stg
12:56:13   File "/tmp/jenkins/workspace/pypowervm/pypowervm/tasks/stor
age.py", line 37, in <module>
12:56:13     from pypowervm.utils import transaction as tx
12:56:13   File "/tmp/jenkins/workspace/pypowervm/pypowervm/utils/tran
saction.py", line 264, in <module>
12:56:13     class WrapperTask(tf_task.BaseTask):
12:56:13 AttributeError: 'module' object has no attribute 'BaseTask'

Change-Id: Iadd15c609789723450692aadbe30025634f848bf