Tolerate storage-less SCSI mappings in find_maps
It is legitimate (though not necessarily useful) to see a SCSI mapping
with a client/server adapter pair, but no backing storage.  Such
mappings were causing find_maps to raise exceptions like:

<snip>
    if find_maps(vios.scsi_mappings, lpar_uuid, stg_elem=storage_elem):
  File "/opt/stack/pypowervm/pypowervm/tasks/scsi_mapper.py", line 312,
in find_maps
    if match_func(existing_scsi_map.backing_storage):
  File "/opt/stack/pypowervm/pypowervm/tasks/scsi_mapper.py", line 293,
in <lambda>
    match_func = lambda stg_el: (stg_el.schema_type ==
stg_elem.schema_type
AttributeError: 'NoneType' object has no attribute 'schema_type'

This change set adds an additional check to tolerate this situation, and
unit test changes to prove tolerance across other methods.

Change-Id: Ic586c73d9f9ef94d63de858c3b30373ed2fd5dbe